import { NextResponse } from "next/server";
import nodemailer from "nodemailer";

export async function sendEmail({email,name,summary,type,}: {email: string;name: string; summary: string; type: "summary" | "welcome" | "reset";}) {
  try {
    const port = parseInt(process.env.SMTP_PORT || "587");
    const secure = port === 465;

    const transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST,
      port,
      secure,
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS,
      },
    });

    let subject = "";
    let text = "";
    let html = "";

    switch (type) {
      case "welcome":
        subject = "Welcome to Doctorally!";
        text = `Dear ${name},\n\nWelcome to Doctorally! We're thrilled to have you on board.\n\n— The Doctorally Team`;
        html = `
          <div style="font-family: Arial, sans-serif; background: #f9f9f9; padding: 20px;">
            <div style="max-width: 600px; margin: auto; background: #ffffff; border-radius: 8px; padding: 20px; box-shadow: 0 4px 12px rgba(0,0,0,0.1);">
              <h2 style="color: #1f3c88; text-align: center; margin-bottom: 20px;">Welcome to Doctorally</h2>
              <p style="font-size: 15px; color: #555;">Dear <b>${name}</b>,</p>
              <p style="font-size: 15px; color: #555;">
                We're thrilled to have you on board. Start generating summaries and managing reports seamlessly.
              </p>
              <p style="font-size: 14px; color: #777; text-align: center; margin-top: 30px;">
                — The Doctorally Team
              </p>
            </div>
          </div>
        `;
        break;

      case "reset":
        subject = "Doctorally Password Reset Request";
        text = `Hi ${name},\n\nReset your password here: ${summary}\n\n— The Doctorally Team`;
        html = `
          <div style="font-family: Arial, sans-serif; background: #f9f9f9; padding: 20px;">
            <div style="max-width: 600px; margin: auto; background: #ffffff; border-radius: 8px; padding: 20px; box-shadow: 0 4px 12px rgba(0,0,0,0.1);">
              <h2 style="color: #1f3c88; text-align: center; margin-bottom: 20px;">Password Reset</h2>
              <p style="font-size: 15px; color: #555;">Hi <b>${name}</b>,</p>
              <p style="font-size: 15px; color: #555;">
                We received a request to reset your password. Click the link below:
              </p>
              <p style="text-align:center; margin: 20px 0;">
                <a href="${summary}" style="padding:10px 20px; background:#1f3c88; color:#fff; text-decoration:none; border-radius:6px;">Reset Password</a>
              </p>
              <p style="font-size: 14px; color: #777; text-align: center; margin-top: 30px;">
                — The Doctorally Team
              </p>
            </div>
          </div>
        `;
        break;

      default: // summary
        subject = "Here is your valuable Doctorally generated summary!";
        text = `Dear ${name},\n\nHere is your valuable Doctorally generated summary:\n\n${summary}\n\n— The Doctorally Team`;
        html = `
          <div style="font-family: Arial, sans-serif; background: #f9f9f9; padding: 20px;">
            <div style="max-width: 600px; margin: auto; background: #ffffff; border-radius: 8px; padding: 20px; box-shadow: 0 4px 12px rgba(0,0,0,0.1);">
              <h2 style="color: #1f3c88; text-align: center; margin-bottom: 20px;">Doctorally Report Summary</h2>
              <p style="font-size: 15px; color: #555;">Dear <b>${name}</b>,</p>
              <p style="font-size: 15px; color: #555;">
                Below is your valuable summary generated by <b>Doctorally</b>:
              </p>
              <div style="margin: 20px 0; padding: 15px; background: #f0f4ff; border-left: 4px solid #1f3c88; border-radius: 6px;">
                <p style="margin: 0; font-size: 15px; color: #333;">
                  ${summary}
                </p>
              </div>
              <p style="font-size: 14px; color: #777; text-align: center; margin-top: 30px;">
                — The Doctorally Team
              </p>
            </div>
          </div>
        `;
        break;
    }

    await transporter.sendMail({
      from: `"Doctorally" <${process.env.SMTP_USER}>`,
      to: email,
      subject,
      text,
      html,
    });

    return { success: true };
  } catch (err) {
    console.error("Email sending failed", err);
    return { success: false, error: "Email failed to send" };
  }
}

// Optional: default export API route for client-side fetch
export async function POST(req: Request) {
  try {
    const { email, name, summary, type } = await req.json();
    const result = await sendEmail({ email, name, summary, type });
    return NextResponse.json(result);
  } catch (err) {
    console.error("Send email API failed", err);
    return NextResponse.json({ success: false, error: "Email failed to send" }, { status: 500 });
  }
}
