import { NextResponse } from "next/server";
import nodemailer from "nodemailer";

export async function POST(req: Request) {
  try {
    const { recipient, summary, userName } = await req.json(); // <-- get user's name

    const port = parseInt(process.env.SMTP_PORT || "587");
    const secure = port === 465;

    const transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST,
      port,
      secure,
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS,
      },
    });

    await transporter.sendMail({
      from: `"Doctorally" <${process.env.SMTP_USER}>`,
      to: recipient,
      subject: "Here is your valuable Doctorally generated summary!",
      text: `Dear ${userName},\n\nHere is your valuable Doctorally generated summary:\n\n${summary}\n\n— The Doctorally Team`,
      html: `
        <div style="font-family: Arial, sans-serif; background: #f9f9f9; padding: 20px;">
          <div style="max-width: 600px; margin: auto; background: #ffffff; border-radius: 8px; padding: 20px; box-shadow: 0 4px 12px rgba(0,0,0,0.1);">
            <h2 style="color: #1f3c88; text-align: center; margin-bottom: 20px;">Doctorally Report Summary</h2>
            <p style="font-size: 15px; color: #555; line-height: 1.6;">
              Dear <b>${userName}</b>,
            </p>
            <p style="font-size: 15px; color: #555; line-height: 1.6;">
              Below is your valuable summary generated by <b>Doctorally</b>:
            </p>
            <div style="margin: 20px 0; padding: 15px; background: #f0f4ff; border-left: 4px solid #1f3c88; border-radius: 6px;">
              <p style="margin: 0; font-size: 15px; color: #333; line-height: 1.6;">
                ${summary}
              </p>
            </div>
            <p style="font-size: 14px; color: #777; line-height: 1.6; text-align: center; margin-top: 30px;">
              — The Doctorally Team
            </p>
          </div>
        </div>
      `,
    });

    return NextResponse.json({ success: true });
  } catch (err) {
    console.error("Email sending failed", err);
    return NextResponse.json({ success: false, error: "Email failed to send" }, { status: 500 });
  }
}
